### ISSUE TITLE
zero_to_fp32.py 权重转换失败

### ISSUE THREAD

**Issue by RuohaoYan** [ssbuild/rlhf_llm#7]
│ /data1/yrh/llm_rlhf/ilql_rlhf/zero_to_fp32.py:498 in get_fp32_state_dict_from_zero_checkpoint    │
│                                                                                                  │
│   495 │   │   │   with open(latest_path, 'r') as fd:                                             │
│   496 │   │   │   │   tag = fd.read().strip()                                                    │
│   497 │   │   else:                                                                              │
│ ❱ 498 │   │   │   raise ValueError(f"Unable to find 'latest' file at {latest_path}")             │
│   499 │                                                                                          │
│   500 │   ds_checkpoint_dir = os.path.join(checkpoint_dir, tag)     

ValueError: Unable to find 'latest' file 

修改为latest

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

**Comment by ssbuild** [comment]
路径错了吧

**Comment by RuohaoYan** [comment]
修改路径后会出现：UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte错误
ckpt转pt

**Comment by ssbuild** [comment]
路径不包含中文试试

**Comment by RuohaoYan** [comment]
路径不包含中文，是否是zero_to_fp32.py的版本发生了变化？我使用的最新版

**Comment by RuohaoYan** [comment]
ckpt文件是训练生成的，
4.0G	epoch1-step0.ckpt
4.0G	epoch2-step0.ckpt
4.0G	epoch3-step0.ckpt
4.0G	epoch4-step0.ckpt
4.0G	epoch5-step0.ckpt
4.0G	epoch6-step0.ckpt
4.0G	epoch7-step0.ckpt
4.0G	latest
4.0G	latest1
我将最后一个ckpt文件修改名字为latest

**Comment by ssbuild** [comment]
这种不是deepspeed权重 ，不需要转换。

**Comment by RuohaoYan** [comment]
抱歉，是我理解有误，请问下面的best.pt如何获取呢？
    if deep_config is None:
        train_weight = './best_ckpt/best.pt'
    else:
        # 建议直接使用转换脚本命
        # cd best_ckpt/last.ckpt
        # python zero_to_fp32.py . best.pt
        train_weight = './best_ckpt/last.ckpt/best.pt'

**Comment by ssbuild** [comment]
deepspeed权重转换下，否则.ckpt也好.pt也好，填写文件名全路径，lora只填写路径，

**Comment by RuohaoYan** [comment]
感谢您的解答
