### ISSUE TITLE
Error(s) in loading state_dict for BloomForCausalLM: 	

### ISSUE THREAD

**Issue by RuohaoYan** [ssbuild/rlhf_llm#8]
当加载train.py保存的bloom-350 ckpt模型进行infer_finetuning.py时报错，错误信息 size mismatch for word_embeddings.weight: copying a param with shape torch.Size([250880, 1024]) from checkpoint, the shape in current model is torch.Size([250680, 1024]).原因似乎是bloom词表导致的问题，我在[https://github.com/microsoft/DeepSpeedExamples/issues/421](url)看到了相似的问题，但尚未找到解决方案

**Comment by YRH0** [comment]
[https://github.com/microsoft/DeepSpeedExamples/issues/421](url)

**Comment by ssbuild** [comment]
新引入的bug , 已fixed

**Comment by RuohaoYan** [comment]
train.py 似乎没有变动，生成的bloom词表size是250680，使用infer_finetuning.py加载时存在如下错误

RuntimeError: Error(s) in loading state_dict for BloomForCausalLM:
        size mismatch for word_embeddings.weight: copying a param with shape torch.Size([250880, 1024]) from checkpoint, the shape 
in current model is torch.Size([250680, 1024]).

**Comment by ssbuild** [comment]
你用的哪个项目 reward ?

**Comment by RuohaoYan** [comment]
我尝试修改了train.py中MyILQLTransformer传入的new_num_tokens
    pl_model = MyILQLTransformer(config=config,model_args=model_args,training_args=training_args,lora_args=lora_args,ilql_args=ilql_args,
                                 quantization_config=global_args["quantization_config"],
                                 load_in_8bit=global_args["load_in_8bit"],
                                 device_map={"": trainer.local_rank} if trainer.world_size > 1 else "auto",
                                 torch_dtype=torch.float16,
                                 new_num_tokens= config.vocab_size,  # 可能扩充词 len(tokenizer)
                                 )
出现了如下错误：
发生异常: AttributeError
'BloomForCausalLM' object has no attribute 'get_llm_model'
  File "/data1/yrh/llm_rlhf/ilql_rlhf/infer_finetuning.py", line 62, in <module>
    response = MyILQLTransformer.generate(model, query=text, tokenizer=tokenizer, max_length=512,

**Comment by RuohaoYan** [comment]
> 你用的哪个项目 reward ?

我直接修改了ilql_rlhf/infer_finetuning.py文件

**Comment by ssbuild** [comment]
的确，还是num_new_token 引起的， 更新下代码 然后
pip uninstall aigc_zoo 
pip install -U -r requirements.txt
试试

**Comment by RuohaoYan** [comment]
可以正常运行了[点赞]
